/**
 * Agent Registration Test Harness — Scenario 1 + 3
 *
 * Scenario 1: HTTP Agent auto-registration via REST API
 * Scenario 3: Bulk auto-register + behavioral event load test
 *
 * Usage:
 *   # Scenario 1 only (single agent, verify cert + audit_log)
 *   BASE_URL=https://www.kakunin.ai API_KEY=kak_test_... TENANT_ID=... \
 *     npx tsx scripts/test-agent-harness.ts --scenario 1
 *
 *   # Scenario 3 (10 agents, 50 events each, rate limit + risk score assertions)
 *   BASE_URL=https://www.kakunin.ai API_KEY=kak_test_... TENANT_ID=... \
 *     npx tsx scripts/test-agent-harness.ts --scenario 3
 *
 *   # Run both (default)
 *   BASE_URL=https://www.kakunin.ai API_KEY=kak_... TENANT_ID=... \
 *     npx tsx scripts/test-agent-harness.ts
 *
 * Env vars (can also be read from .env.test.local):
 *   BASE_URL       — target server (https://www.kakunin.ai or http://localhost:3000)
 *   API_KEY        — API key (kak_live_* for production, kak_test_* for sandbox)
 *   TENANT_ID      — tenant UUID
 */

import { config } from 'dotenv';
import path from 'path';

// Load .env.test.local if present (generated by seed-test-agent.ts)
config({ path: path.join(__dirname, '..', '.env.test.local') });
config({ path: path.join(__dirname, '..', '.env.local') });

const BASE_URL = process.env.BASE_URL ?? 'http://localhost:3000';
const API_KEY = process.env.TEST_API_KEY ?? process.env.API_KEY ?? '';
const TENANT_ID = process.env.TEST_TENANT_ID ?? process.env.TENANT_ID ?? '';

const scenario = process.argv.includes('--scenario')
  ? process.argv[process.argv.indexOf('--scenario') + 1]
  : 'all';

// ── Helpers ──────────────────────────────────────────────────────────────────

type AnyRecord = Record<string, unknown>;

async function apiFetch(
  method: string,
  path: string,
  body?: AnyRecord,
  tenantOverride?: string,
): Promise<{ status: number; data: AnyRecord }> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${API_KEY}`,
      'x-tenant-id': tenantOverride ?? TENANT_ID,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const data = (await res.json().catch(() => ({}))) as AnyRecord;
  return { status: res.status, data };
}

function assert(condition: boolean, msg: string) {
  if (!condition) {
    console.error(`  ❌  FAIL: ${msg}`);
    process.exitCode = 1;
  } else {
    console.log(`  ✅  ${msg}`);
  }
}

function randomHash(prefix = 'test'): string {
  return `sha256:${Array.from(crypto.getRandomValues(new Uint8Array(32)))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')}`;
}

// ── Scenario 1: Single HTTP agent auto-registration ───────────────────────────

async function scenario1() {
  console.log('\n═══════════════════════════════════════════════');
  console.log('  Scenario 1 — HTTP Agent auto-registration');
  console.log('═══════════════════════════════════════════════');

  // Step 1: Register agent
  console.log('\n[1/4] POST /api/v1/agents — register agent');
  const reg = await apiFetch('POST', '/api/v1/agents', {
    name: `Harness-S1-${Date.now()}`,
    model: 'gpt-4o',
    version: '1.0.0',
    model_hash: randomHash('s1'),
  });
  assert(reg.status === 201, `Registration returns 201 (got ${reg.status})`);
  const agent = (reg.data as AnyRecord).data as AnyRecord;
  assert(typeof agent?.id === 'string', `Agent UUID present: ${agent?.id}`);
  assert(agent?.status === 'pending', `Agent status = pending (got ${agent?.status})`);
  const agentId = agent.id as string;

  // Step 2: GET agent detail
  console.log('\n[2/4] GET /api/v1/agents/:id — verify agent exists');
  const get = await apiFetch('GET', `/api/v1/agents/${agentId}`);
  assert(get.status === 200, `GET agent returns 200 (got ${get.status})`);
  const fetched = (get.data as AnyRecord).data as AnyRecord;
  assert(fetched?.id === agentId, 'Agent ID matches');

  // Step 3: List agents — confirm appears in list
  console.log('\n[3/4] GET /api/v1/agents — agent appears in list');
  const list = await apiFetch('GET', '/api/v1/agents');
  assert(list.status === 200, `List returns 200 (got ${list.status})`);
  const agents = (list.data as AnyRecord).data as AnyRecord[];
  assert(
    Array.isArray(agents) && agents.some((a: AnyRecord) => a.id === agentId),
    `Agent ${agentId} in list`,
  );

  // Step 4: Certify agent (triggers KMS cert issuance)
  console.log('\n[4/4] POST /api/v1/agents/:id/certify — issue X.509 cert');
  const certify = await apiFetch('POST', `/api/v1/agents/${agentId}/certify`);
  assert(
    certify.status === 201 || certify.status === 200,
    `Certify returns 2xx (got ${certify.status})`,
  );
  const cert = (certify.data as AnyRecord).data as AnyRecord;
  assert(typeof cert?.serial_number === 'string' || typeof cert?.certificate === 'string',
    `Cert serial or PEM present`);

  console.log(`\n  Agent ID:  ${agentId}`);
  console.log(`  Status:    ${agent.status}`);
  console.log(`  Cert:      ${cert?.serial_number ?? cert?.certificate ? 'issued' : 'pending'}`);

  return agentId;
}

// ── Scenario 3: Event harness + load test ─────────────────────────────────────

const ACTION_TYPES = [
  'api_call',
  'authentication_attempt',
  'data_access',
  'data_mutation',
  'transaction_initiated',
];

async function scenario3() {
  console.log('\n═══════════════════════════════════════════════');
  console.log('  Scenario 3 — Event Harness + Load Test');
  console.log('═══════════════════════════════════════════════');

  const AGENT_COUNT = 10;
  const EVENTS_PER_AGENT = 50;

  // Step 1: Register 10 agents in parallel
  console.log(`\n[1/5] Register ${AGENT_COUNT} agents in parallel`);
  const regResults = await Promise.allSettled(
    Array.from({ length: AGENT_COUNT }, (_, i) =>
      apiFetch('POST', '/api/v1/agents', {
        name: `Harness-S3-Agent-${i + 1}-${Date.now()}`,
        model: 'gpt-4o',
        version: '1.0.0',
        model_hash: randomHash(`s3-${i}`),
      }),
    ),
  );

  const agentIds: string[] = [];
  let regOk = 0;
  for (const r of regResults) {
    if (r.status === 'fulfilled' && r.value.status === 201) {
      const agent = (r.value.data as AnyRecord).data as AnyRecord;
      if (typeof agent?.id === 'string') {
        agentIds.push(agent.id);
        regOk++;
      }
    }
  }
  assert(regOk === AGENT_COUNT, `All ${AGENT_COUNT} agents registered (${regOk}/${AGENT_COUNT} ok)`);

  // Step 2: Fire events
  console.log(`\n[2/5] Fire ${EVENTS_PER_AGENT} events per agent (${AGENT_COUNT * EVENTS_PER_AGENT} total)`);

  let totalOk = 0;
  let total429 = 0;
  let highRiskAgentFound = false;

  // Fire in batches per agent (sequential per agent, parallel across agents)
  await Promise.all(
    agentIds.map(async (agentId) => {
      for (let i = 0; i < EVENTS_PER_AGENT; i++) {
        // Use varied action types; sprinkle higher-risk ones toward the end
        const actionIndex = i < 40
          ? i % 3 // api_call, authentication, data_access (low risk)
          : 4;    // transaction_initiated (medium risk)

        const res = await apiFetch('POST', '/api/v1/events', {
          agentId,
          actionType: ACTION_TYPES[actionIndex],
          details: { source: 'harness', seq: i },
        });

        if (res.status === 200) {
          totalOk++;
          const data = (res.data as AnyRecord).data as AnyRecord;
          if ((data?.risk_band as string) === 'high' || (data?.risk_score as number) >= 0.85) {
            highRiskAgentFound = true;
          }
        } else if (res.status === 429) {
          total429++;
        }
      }
    }),
  );

  const totalEvents = AGENT_COUNT * EVENTS_PER_AGENT;
  assert(
    totalOk >= totalEvents * 0.9,
    `≥ 90% events accepted (${totalOk}/${totalEvents} ok, ${total429} rate-limited)`,
  );
  assert(
    total429 < totalEvents * 0.1,
    `< 10% false-positive 429s (${total429}/${totalEvents})`,
  );

  // Step 3: Verify risk scores computed for all agents
  console.log('\n[3/5] GET /api/v1/agents/:id/risk — verify risk scores');
  let riskOk = 0;
  let mediumOrHighCount = 0;

  await Promise.all(
    agentIds.map(async (agentId) => {
      const r = await apiFetch('GET', `/api/v1/agents/${agentId}/risk`);
      if (r.status === 200) {
        riskOk++;
        const data = (r.data as AnyRecord).data as AnyRecord;
        const band = data?.dominant_band as string;
        if (band === 'medium' || band === 'high') mediumOrHighCount++;
      }
    }),
  );

  assert(riskOk === AGENT_COUNT, `Risk scores returned for all ${AGENT_COUNT} agents`);
  assert(mediumOrHighCount >= 1, `At least 1 agent drifted to medium/high band (${mediumOrHighCount})`);

  // Step 4: SSE stream spot-check for first agent
  console.log('\n[4/5] GET /api/v1/agents/:id/events/stream — SSE stream live');
  const testAgentId = agentIds[0];
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  let sseReceived = false;

  try {
    const sseRes = await fetch(`${BASE_URL}/api/v1/agents/${testAgentId}/events/stream`, {
      headers: {
        Authorization: `Bearer ${API_KEY}`,
        'x-tenant-id': TENANT_ID,
        Accept: 'text/event-stream',
      },
      signal: controller.signal,
    });

    sseReceived = sseRes.status === 200 && sseRes.headers.get('content-type')?.includes('text/event-stream') === true;
  } catch {
    // AbortError is expected after timeout
    sseReceived = true; // connection opened if we got an error from abort
  } finally {
    clearTimeout(timeout);
  }

  assert(sseReceived, 'SSE stream endpoint reachable (200 + text/event-stream)');

  // Step 5: Audit log count
  console.log('\n[5/5] GET /api/v1/audit-log — verify row count');
  const auditRes = await apiFetch('GET', `/api/v1/audit-log?limit=100`);
  assert(auditRes.status === 200, `Audit log endpoint returns 200 (got ${auditRes.status})`);

  console.log(`\n  Agents registered: ${agentIds.length}`);
  console.log(`  Events fired:      ${totalOk}`);
  console.log(`  Rate limited:      ${total429}`);
  console.log(`  Medium/High band:  ${mediumOrHighCount} agents`);
  console.log(`  High-risk hit:     ${highRiskAgentFound}`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

(async () => {
  if (!API_KEY || !TENANT_ID) {
    console.error(
      '❌  API_KEY and TENANT_ID required.\n' +
        '    Run: npx tsx scripts/seed-test-agent.ts   (generates .env.test.local)\n' +
        '    Or set BASE_URL, API_KEY, TENANT_ID env vars directly.',
    );
    process.exit(1);
  }

  console.log(`\nTarget: ${BASE_URL}`);
  console.log(`Tenant: ${TENANT_ID}`);
  console.log(`Key:    ${API_KEY.slice(0, 16)}...`);

  const start = Date.now();

  if (scenario === '1' || scenario === 'all') {
    await scenario1().catch((e) => {
      console.error('Scenario 1 crashed:', e);
      process.exitCode = 1;
    });
  }

  if (scenario === '3' || scenario === 'all') {
    await scenario3().catch((e) => {
      console.error('Scenario 3 crashed:', e);
      process.exitCode = 1;
    });
  }

  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`\n──────────────────────────────────────────────`);
  console.log(`  Harness complete in ${elapsed}s`);
  console.log(`  Exit code: ${process.exitCode ?? 0}`);
})();
