-- Migration: add integration_connections for outbound telemetry/CI integrations
-- Week: v2 (P1 prerequisite)
-- Reason: shared table for tenant-configured outbound integrations — v2 OTLP
--         observability exporter ('otlp') and the GitHub Actions cert gate
--         ('github'). Holds encrypted credentials + per-connection sync state.
--         See docs/V2_BLUEPRINT.md §4. RA-174 (blocks P1: RA-178..181).
-- Author: auto-generated by /supabase-migration
-- Date: 2026-05-30

CREATE TABLE public.integration_connections (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     UUID        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  provider      TEXT        NOT NULL CHECK (provider IN ('otlp', 'github')),
  -- Destination URL for outbound posts (OTLP collector endpoint, etc.).
  -- MUST be passed through assertSafeUrl() (src/lib/security/url-guard.ts)
  -- before any outbound fetch — SSRF guard, rejects private/link-local hosts.
  endpoint_url  TEXT,
  -- AES-256-GCM ciphertext (format <iv_hex>:<authtag_hex>:<ciphertext_hex>),
  -- encrypted with CREDENTIAL_ENCRYPTION_KEY via lib/credentials/crypto.ts.
  -- Never returned in API responses.
  headers_enc   TEXT,
  api_key_enc   TEXT,
  config        JSONB       NOT NULL DEFAULT '{}',
  enabled       BOOLEAN     NOT NULL DEFAULT true,
  -- Cursor for the cron sweep — rows changed after this are shipped next run.
  last_sync     TIMESTAMPTZ,
  -- Last error surfaced to the tenant (connection test / export failure).
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- At most one enabled connection per (tenant, provider).
CREATE UNIQUE INDEX integration_connections_tenant_provider_idx
  ON public.integration_connections (tenant_id, provider)
  WHERE enabled = true;

-- Cron sweep reads enabled rows ordered by last_sync — support the scan.
CREATE INDEX integration_connections_sweep_idx
  ON public.integration_connections (provider, last_sync)
  WHERE enabled = true;

COMMENT ON COLUMN public.integration_connections.headers_enc IS
  'AES-256-GCM encrypted JSON of custom outbound headers (e.g. OTLP auth). Format: <iv_hex>:<authtag_hex>:<ciphertext_hex>. Encrypted with CREDENTIAL_ENCRYPTION_KEY.';
COMMENT ON COLUMN public.integration_connections.api_key_enc IS
  'AES-256-GCM encrypted API key / token (format <iv_hex>:<authtag_hex>:<ciphertext_hex>). Encrypted with CREDENTIAL_ENCRYPTION_KEY.';
COMMENT ON COLUMN public.integration_connections.endpoint_url IS
  'Outbound destination URL. MUST pass assertSafeUrl() before any fetch (SSRF guard).';

ALTER TABLE public.integration_connections ENABLE ROW LEVEL SECURITY;

-- Tenants can read their own connections (encrypted creds masked in app layer).
CREATE POLICY "integration_connections_select" ON public.integration_connections
  FOR SELECT USING (
    tenant_id = (
      SELECT id FROM public.tenants
      WHERE email = auth.email()
      LIMIT 1
    )
  );

-- No direct insert/update/delete from client — service role only.
CREATE POLICY "integration_connections_service_role" ON public.integration_connections
  FOR ALL USING (auth.role() = 'service_role');

-- GRANTs — REQUIRED (PostgREST blocks access without these). Never grant anon.
GRANT SELECT ON public.integration_connections TO authenticated;
GRANT ALL ON public.integration_connections TO service_role;
