-- Migration: add 'output_content_risk' to behavior_events action_type CHECK
-- Week: v2 (P3b)
-- Reason: the FME content-risk layer scores what an agent SAID (manipulation /
--         deception in output text) and feeds it back as a behavioral event,
--         mapped to EU AI Act Article 5 (prohibited manipulative practices).
--         Scored async, off the /v1/events hot path. RA-186.
-- Author: auto-generated by /supabase-migration
-- Date: 2026-05-30

ALTER TABLE behavior_events DROP CONSTRAINT IF EXISTS behavior_events_action_type_check;

ALTER TABLE behavior_events ADD CONSTRAINT behavior_events_action_type_check CHECK (action_type IN (
  'api_call', 'authentication_attempt', 'authentication_failure',
  'data_access', 'data_mutation', 'transaction_initiated',
  'transaction_anomaly', 'unauthorized_access_attempt',
  'message_signed', 'message_verification_failed',
  'kill_switch_activated', 'output_content_risk'
));
