-- Migration: index to support forensic queries by agent + risk
-- Week: v2 (P3a)
-- Reason: GET /v1/agents/:id/forensics filters an agent's behavior_events by
--         min risk over a time range. The existing (agent_id, occurred_at DESC)
--         index covers time-only queries; this adds a risk-ordered composite so
--         "high-risk events for this agent" forensic pulls stay index-served.
--         RA-185.
-- Author: auto-generated by /supabase-migration
-- Date: 2026-05-30

CREATE INDEX IF NOT EXISTS idx_behavior_events_agent_risk
  ON public.behavior_events (agent_id, risk_score DESC, occurred_at DESC);
