-- Migration: add environment column for sandbox/production data isolation
-- Week: 2 (Sandbox infrastructure — RA-118)
-- Reason: Enable test data separation, on-demand reset API, nightly retention cleanup
-- Author: auto-generated by /migrate command
-- Date: 2026-05-23

-- Add environment column to all core tables
-- Default to 'production'; sandbox writes set explicitly via middleware flag
ALTER TABLE agents ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;
ALTER TABLE certificates ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;
ALTER TABLE behavior_events ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;
ALTER TABLE audit_log ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;
ALTER TABLE webhooks ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;
ALTER TABLE compliance_reports ADD COLUMN environment TEXT DEFAULT 'production' NOT NULL;

-- Indexes for retention cleanup queries (sandbox data older than 7 days)
CREATE INDEX idx_agents_env_created ON agents(environment, created_at) WHERE environment = 'sandbox';
CREATE INDEX idx_behavior_events_env_created ON behavior_events(environment, created_at) WHERE environment = 'sandbox';
CREATE INDEX idx_audit_log_env_created ON audit_log(environment, created_at) WHERE environment = 'sandbox';

-- No new RLS policies needed — existing tenant_id RLS already isolates sandbox per-tenant
-- environment column just adds organizational tagging, doesn't change isolation guarantees
